### ISSUE TITLE
Memory leaks when first operation of chain throws exception

### ISSUE THREAD

**Issue by akkrat** [strongself/COOperation#5]
Test project attached to this message. (It's a copy of master branch where I simplified `execute` method of `FirstViewController` and decreased operations count.)

[COOperation-leaks.zip](https://github.com/rambler-digital-solutions/COOperation/files/741819/COOperation-leaks.zip)
![2017-01-31](https://cloud.githubusercontent.com/assets/13553902/22463409/868b8d50-e7c2-11e6-8702-fd6e794215d2.png)

**Comment by novixon** [comment]
@akkrat Thanks for your investigation. This bug is fixed in version 0.0.3!
